M48
; DRILL file {KiCad (6.0.9)} date Wed Feb 22 17:41:16 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-22T17:41:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.300
%
G90
G05
T1
X37.75Y-113.499
X43.53Y-113.499
T2
X22.55Y-113.743
T3
X2.54Y-100.33
X17.78Y-49.53
X45.72Y-49.53
X50.8Y-101.6
T0
M30
